model_name: dense_net_hybrid
parameters:
  augmentation_strength:
    log: false
    options:
    - none
    - light
    - medium
    - strong
    type: categorical
    values:
    - none
    - light
    - medium
    - strong
  batch_size:
    log: false
    options:
    - 8
    - 16
    - 32
    - 64
    type: categorical
    values:
    - 8
    - 16
    - 32
    - 64
  compression:
    high: 0.8
    log: false
    low: 0.3
    type: float
    values:
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
  criterion.name:
    log: false
    options:
    - focal
    type: categorical
    values:
    - focal
  dense_block_config:
    log: false
    options:
    - standard
    - compact
    - wide
    type: categorical
    values:
    - standard
    - compact
    - wide
  dropout_rate:
    high: 0.5
    log: false
    low: 0.0
    type: float
    values:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
  epoch:
    high: 50
    log: false
    low: 10
    type: int
    values:
    - 10
    - 20
    - 30
    - 40
    - 50
  feature_fusion_dropout:
    high: 0.3
    log: false
    low: 0.0
    type: float
    values:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
  grad_clip_norm:
    high: 2.0
    log: false
    low: 0.5
    type: float
    values:
    - 0.5
    - 1.0
    - 1.5
    - 2.0
  growth_rate:
    high: 48
    log: false
    low: 16
    type: int
    values:
    - 16
    - 24
    - 32
    - 40
    - 48
  img_size:
    log: false
    options:
    - 224
    - 256
    - 288
    - 320
    type: categorical
    values:
    - 224
    - 256
    - 288
    - 320
  mixup_alpha:
    high: 0.4
    log: false
    low: 0.0
    type: float
    values:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
  normalize:
    log: false
    options:
    - true
    - false
    type: categorical
    values:
    - true
    - false
  onecycle.max_lr_multiplier:
    high: 20.0
    log: false
    low: 5.0
    type: float
    values:
    - 5.0
    - 10.0
    - 15.0
    - 20.0
  optim.lr:
    high: 0.01
    log: true
    low: 1.0e-05
    type: float
    values:
    - 1.0e-05
    - 5.0e-05
    - 0.0001
    - 0.0002
    - 0.0005
    - 0.001
    - 0.005
    - 0.01
  optim.name:
    log: false
    options:
    - adam
    - adamw
    - sgd
    type: categorical
    values:
    - adam
    - adamw
    - sgd
  optim.weight_decay:
    high: 0.001
    log: true
    low: 1.0e-06
    type: float
    values:
    - 1.0e-06
    - 1.0e-05
    - 5.0e-05
    - 0.0001
    - 0.0005
    - 0.001
  patience:
    high: 15
    log: false
    low: 3
    type: int
    values:
    - 3
    - 5
    - 7
    - 10
    - 15
  plateau.factor:
    high: 0.8
    log: false
    low: 0.1
    type: float
    values:
    - 0.1
    - 0.3
    - 0.5
    - 0.8
  plateau.patience:
    high: 8
    log: false
    low: 2
    type: int
    values:
    - 2
    - 3
    - 5
    - 8
  scheduler:
    log: false
    options:
    - cosine
    - onecycle
    - plateau
    - null
    type: categorical
    values:
    - cosine
    - onecycle
    - plateau
    - null
  statistical_features_weight:
    high: 1.0
    log: false
    low: 0.1
    type: float
    values:
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 1.0
tuner_configs:
  pytorch_optuna:
    direction: maximize
    n_trials: 15
    random_state: 42
    scoring: f1
    timeout: 3600
    val_size: 0.2
