model_name: svm
parameters:
  C:
    high: 100.0
    log: true
    low: 0.1
    type: float
    values:
    - 0.1
    - 1.0
    - 10.0
    - 100.0
  degree:
    high: 5
    log: false
    low: 2
    type: int
    values:
    - 2
    - 3
    - 4
  gamma:
    log: false
    options:
    - scale
    - auto
    type: categorical
    values:
    - scale
    - auto
  kernel:
    log: false
    options:
    - linear
    - poly
    - rbf
    - sigmoid
    type: categorical
    values:
    - linear
    - rbf
    - poly
  probability:
    log: false
    options:
    - true
    - false
    type: categorical
    values:
    - true
tuner_configs:
  sklearn_gridsearch:
    cv: 3
    n_jobs: -1
    scoring: f1
  sklearn_optuna:
    cv: 5
    direction: maximize
    n_trials: 500
    scoring: f1_macro
